name: Python Rye Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  rye-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rye
        run: |
          curl -sSf https://rye-up.com/get | bash

      - name: Sync dependencies
        run: |
          rye sync

      - name: Linting
        run: |
          rye run lint
